config/routes.rb
Rails.application.routes.draw do

  root 'home#index'
  resources :notices
  resources :qnas
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  devise_scope :user do
    get '/users/auth/kakao', to: 'users/omniauth_callbacks#kakao'
    get '/users/auth/kakao/callback', to: 'users/omniauth_callbacks#kakao_auth'
  end
  get '/info' => 'home#info'

  get '/products/index_penalty'   => 'products#index_penalty'
  get '/products/new_penalty'     => 'products#new_penalty'
  resources :products
 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  get '/product_new'  => 'products#new_map'
  post '/product_map' => 'products#create_map'
    
  get '/smovesmoveadmin'                     => 'admin_pages#index'
  get '/smovesmoveadmin/show_user'           => 'admin_pages#show_user'
  get '/smovesmoveadmin/show_nsmoking'       => 'admin_pages#show_nsmoking'
  get '/smovesmoveadmin/show_smoke_place'    => 'admin_pages#show_smoke_place'
  get '/smovesmoveadmin/show_qna'            => 'admin_pages#show_qna'
  get '/smovesmoveadmin/show_notice'         => 'admin_pages#show_notice'
  get '/smovesmoveadmin/show_penalty_place'  => 'admin_pages#show_penalty_place'
  get '/smovesmoveadmin/nsmoking_areas'      => 'admin_pages#nsmoking_areas'
  get '/smovesmoveadmin/login'               => 'admin_pages#login'
  get '/smovesmoveadmin/new_notice'          => 'admin_pages#new_notice'  
    
  get '/smovesmoveadmin/edit_notice'          => 'admin_pages#edit_notice'  

  get '/likes/:product_id/home' => 'home#like_product'
  get '/likes/:product_id/product' => 'products#like_product'
  
    
end

app/models/product.rb
class Product < ApplicationRecord
    mount_uploader :image_address, ImageUploader
    has_many :likes
    has_many :users,through: :likes
    
    paginates_per 6
end

app/controllers/products_controller.rb
 class ProductsController < ApplicationController
  
   before_action :user_pages
   before_action :authenticate_user!, except: [:index, :index_penalty] 
   before_action :set_product, only: [:show, :edit, :update, :destroy]
   
   # GET /products
   # GET /products.json
   def index
     @products = Product.all
      # @products = Product.page params[:page]
    @p = 1
   end
   
   def index_penalty
     @products = Product.all
     @p = 2
   end
 
   # GET /products/1
   # GET /products/1.json
   def show
    @user_likes_product = Like.where(user_id: current_user.id, product_id: @product.id).first if user_signed_in?
     if @product.area_type.eql?("흡연구역")
      @p = 1
     else @product.area_type.eql?("단속구역")
      @p = 2
     end
   end
 
   # GET /products/new
   def new
     @product = Product.new
     @p = 1
     
   end
 
   def new_penalty
     @product = Product.new
     @p = 2
   end
 
   # GET /products/1/edit
   def edit
   end
 

 
   # POST /products
   # POST /products.json
   def create
     @product = Product.new(product_params)
     @product.save
     if @product.area_type.eql?("흡연구역")
       redirect_to "/products"
        flash[:info] = '흡연구역이 등록되었습니다.'
     else
       redirect_to "/products/index_penalty"
       flash[:info] = '단속구역이 등록되었습니다.'
     end
   end
 
   # PATCH/PUT /products/1
   # PATCH/PUT /products/1.json
   def update

   @product.update(product_params)
   redirect_to "/smovesmoveadmin"

   end
 
   # DELETE /products/1
   # DELETE /products/1.json
   def destroy

     @product.destroy
     redirect_to "/smovesmoveadmin"
   
     
   end
   
   def new_map
   end
   def create_map
         u1 = Product.new
         u1.latitude =  session[:map_lat]
         u1.longitude = session[:map_lng]
         u1.area_name = params[:area_name]
         u1.address = params[:address]
         u1.save
         redirect_to "/"
   end
   
  def like_product
    #현재 유저와 params에 담긴 movie간의 좋아요 관계를 설정한다.
    @like = Like.where(user_id: current_user.id, product_id: params[:product_id]).first
    if @like.nil?
       @like=Like.create(user_id: current_user.id,product_id: params[:product_id])
    else
        @like.destroy
    #만약에 현재 로그인한 유저가 이미 좋아요를 눌렀을 경우
    #해당 Like 인스턴스 삭제
    end
  end
 
   private
     # Use callbacks to share common setup or constraints between actions.
     def set_product
       @product = Product.find(params[:id])
     end
 
     # Never trust parameters from the scary internet, only allow the white list through.
     def product_params
       params.require(:product).permit(:area_type,:area_name,:address,:latitude,:longitude,:description,:image_address)
     end
     
     def user_pages
       @user_pages = true
     end
     
 end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_for(product) do |f| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="py-4 text-center">
  <div class = "from-group mx-auto" style="width:200px">
    위도<br/>
    <%=f.text_field :latitude, id: 'lat' ,class: "form-control"%>
  </div>
  <div class = "from-group mx-auto" style="width:200px">
    경도<br/>
    <%=f.text_field :longitude, id: 'lng' ,class: "form-control"%><br/>
  </div>
  
    <% if @p == 1 %>
  
  <div class = "from-group col-md-6 mx-auto">
    장소 종류<br/>
    <%= f.select :area_type, options_for_select([["흡연구역", "흡연구역"],["단속구역", "단속구역"]]), :class => 'genForm_dropBox' %> <br/><br/>
  </div>
  
    <% elsif @p == 2 %>
    
  <div class = "from-group col-md-6 mx-auto">
    장소 종류<br/>
    <%= f.select :area_type, options_for_select([["단속구역", "단속구역"], ["흡연구역", "흡연구역"]]), :class => 'genForm_dropBox' %> <br/><br/>
  </div>
  
  <% else %>

  <% end %>
  
  <div class = "from-group col-md-6 mx-auto">
    장소명<br/>
    <%=f.text_field :area_name,class: "form-control"%><br/>
  </div>
  <div class = "from-group col-md-6 mx-auto">
    장소 설명<br/>
    <%=f.text_area :description,class: "form-control"%><br/>
  </div>
  <div class = "from-group col-md-3 mx-auto">
    사진 업로드<br/>
    <%=f.file_field :image_address, class: "form-control"%><br/>
  </div>
  <br/>
  <div class="actions">
    <%= f.submit "등록하기",class: 'btn btn-primary'%>
  </div>
</div>
<% end %>

app/views/products/_search.html.erb
<script>

</script>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
        <!-- start head bottom -->
      <div class="bottom">
        <div class="left">
          <h1>등록된 흡연구역 목록</h1>
        </div>
        <div class="right">
          <!--<h1>dashboard /</h1>-->
          <!--<a href="#">page name</a>-->
        </div>
      </div>
      <!-- end head bottom -->
      

<div class ="m-3"><div id="map" style="width:100%;height:300px;z-index: 0;"></div></div>

<script type="text/javascript" src="//dapi.kakao.com/v2/maps/sdk.js?appkey=<%= ENV['DAUM_MAP_API'] %>"></script>
            
      
<div class="card-body">
  <h3 class="m-b-lg"></h3>
    <div class="row">
<% @products.reverse.each do |product|%>
<% if product.area_type.eql?("흡연구역") %>
     <div class="card col-md-4">
  	   <img class="card-img-top" src="<%= product.image_address.thumb.url %>" >
  	 <div class="card-boby text"><br>
  	 <div class="card-block">
  		<h4 class="card-title">장소명 : <%=product.area_name%></h4>
  		
  		    장소 설명 : <%=product.description%> <br>
  		</div>
  		<div class="card-block">
  		    <center>
  	      <%= link_to '자세히보기', product_path(product), class: "btn btn-primary"%>
  	      </center>
  		</div>
  	  </div>
  	</div><!-- END column -->
<% end %>
<% end %>
  </div><!-- .row -->
<!--<1%= paginate @products %>-->
</div>

<% content_for 'javascript_content' do %>
<%= javascript_include_tag params[:controller] %>
<% end %>

<script>
    console.log("content_for");
</script>    


<script>


var mapContainer = document.getElementById('map'), // 지도의 중심좌표
    mapOption = { 
        center: new daum.maps.LatLng(37.4977796, 127.0755652), // 지도의 중심좌표
        level: 4 // 지도의 확대 레벨
    }; 

var map = new daum.maps.Map(mapContainer, mapOption); // 지도를 생성합니다


// HTML5의 geolocation으로 사용할 수 있는지 확인합니다 
if (navigator.geolocation) {
    
    // GeoLocation을 이용해서 접속 위치를 얻어옵니다
    navigator.geolocation.getCurrentPosition(function(position) {
        
        var lat = position.coords.latitude, // 위도
            lon = position.coords.longitude; // 경도
        
        var locPosition = new daum.maps.LatLng(lat, lon), // 마커가 표시될 위치를 geolocation으로 얻어온 좌표로 생성합니다
            message = '<center><div style="padding:5px;">현재 위치!</div></center>'; // 인포윈도우에 표시될 내용입니다
        
        // 마커와 인포윈도우를 표시합니다
        displayMarker(locPosition, message);
            
      });
    
} else { // HTML5의 GeoLocation을 사용할 수 없을때 마커 표시 위치와 인포윈도우 내용을 설정합니다
    
    var locPosition = new daum.maps.LatLng(33.450701, 126.570667),    
        message = 'geolocation을 사용할수 없어요..'
        
    displayMarker(locPosition, message);
}

// 지도에 마커와 인포윈도우를 표시하는 함수입니다
function displayMarker(locPosition, message) {

    // 마커를 생성합니다
    var marker = new daum.maps.Marker({  
        map: map, 
        position: locPosition
    }); 
    
    var iwContent = message, // 인포윈도우에 표시할 내용
        iwRemoveable = true;

    // 인포윈도우를 생성합니다
    var infowindow = new daum.maps.InfoWindow({
        content : iwContent,
        removable : iwRemoveable
    });
    
    // 인포윈도우를 마커위에 표시합니다 
    infowindow.open(map, marker);
    
    // 지도 중심좌표를 접속위치로 변경합니다
    map.setCenter(locPosition);      
}    






var positions = [];
// 커스텀 오버레이에 표시할 컨텐츠 입니다
// 커스텀 오버레이는 아래와 같이 사용자가 자유롭게 컨텐츠를 구성하고 이벤트를 제어할 수 있기 때문에
// 별도의 이벤트 메소드를 제공하지 않습니다 
            //'                <div><a href="http://www.kakaocorp.com/main" target="_blank" class="link">홈페이지</a></div>' + 
// 마커 위에 커스텀오버레이를 표시합니다
// 마커를 중심으로 커스텀 오버레이를 표시하기위해 CSS를 이용해 위치를 설정했습니다
<% @products.each do |product|%>
        var content = '<div class="wrap">' + 
            '    <div class="info">' + 
            '        <div class="title" value= "<%= product.id%>">' + 
            '            <%= product.area_type%>-신고누적(<%= product.likes.count %>)' + 
            '            <div class="close"  title="닫기"></div>' + 
            '        </div>' + 
            '        <div class="body">' + 
            '            <div class="img">' +
            '                <img src="<%= product.image_address%>" width="73" height="70">' +
            '           </div>' + 
            '            <div class="desc">' + 
            '                <div class="ellipsis"><h5><%= product.area_name%></h5></div>' + 
            '    <a href = "/products/<%= product.id %>" class="btn btn-info btn-sm">자세히보기</a>' +
            '            </div>' + 
            '            </div>' + 
            '        </div>' + 
            '    </div>' +    
            '</div>'; 
        var m = "<%= product.area_type%>";
        console.log(m)
    positions.push(
        {
        content: content,
        latlng: new daum.maps.LatLng(<%=product.latitude %>, <%=product.longitude %>),
        imarker: m
        }
    );
<% end %>

console.log(overlay);
var overlay = [];
for (var i = 0 ; i < positions.length; i ++) {
    
    if  (positions[i].imarker=="흡연구역") // "<@%= asset_path 'g2.png' %>"
    var markerImageUrl = "<%= asset_path 'smoking.png' %>"
	    markerImageSize = new daum.maps.Size(30, 41) // 마커 이미지의 크기
	    markerImageOptions = { 
	        offset : new daum.maps.Point(16, 40)// 마커 좌표에 일치시킬 이미지 안의 좌표
	    };

	// 마커 이미지를 생성한다
	var markerImage = new daum.maps.MarkerImage(markerImageUrl, markerImageSize, markerImageOptions);

    var marker = new daum.maps.Marker({
        map: map, 
        image : markerImage,
        position: positions[i].latlng,
        title: i
    });
    
     
    
    console.log(marker);
   overlay[i]= new daum.maps.CustomOverlay({
            content: positions[i].content,
            position: positions[i].latlng
    });
    console.log(overlay.length);
    
    (function(marker, overlay) {
        // 마커에 click 이벤트를 등록하고 마우스 오버 시 인포윈도우를 표시합니다.
           
    daum.maps.event.addListener(marker, 'click', function() {
            var selectedMarker = marker;
            for (var j = 0; j < positions.length; j ++) {
            if (selectedMarker || selectedMarker == marker) {
                overlay[j].setMap(null);
            };
            };
            overlay[marker.getTitle()].setMap(map);
        });
// 커스텀 오버레이를 닫기 위해 호출되는 함수입니다 
        // 마커에 mouseout 이벤트를 등록하고 마우스 아웃 시 인포윈도우를 닫습니다
        daum.maps.event.addListener(marker, 'mouseout', function() {
          $( ".close" ).click( function() {
           overlay[marker.getTitle()].setMap(null); 
            });
        });
    })(marker, overlay);
    
};
</script>
  
  
  
  <!-- panel script -->
  <% content_for 'javascript_content' do %>
  <%= javascript_include_tag params[:controller] %>
  <script>
  console.log("smoking_areas.index");
  </script>
  <% end %>
  

  

<style>
    .wrap {position: absolute;left: 0;bottom: 40px;width: 288px;height: 132px;text-align: left;overflow: hidden;font-size: 12px;font-family: 'Malgun Gothic', dotum, '돋움', sans-serif;line-height: 1.5;}
    .wrap {padding: 0;margin-left: -144px;}
    .wrap .info {width: 286px;height: 120px;border-radius: 5px;border-bottom: 2px solid #ccc;border-right: 1px solid #ccc;overflow: hidden;background: #fff;}
    .wrap .info:nth-child(1) {border: 0;box-shadow: 0px 1px 2px #888;}
    .info .title {padding: 5px 0 0 10px;height: 30px;background: #eee;border-bottom: 1px solid #ddd;font-size: 18px;font-weight: bold;}
    .info .close {position: absolute;top: 10px;right: 10px;color: #888;width: 17px;height: 17px;background: url('http://t1.daumcdn.net/localimg/localimages/07/mapapidoc/overlay_close.png');}
    .info .close:hover {cursor: pointer;}
    .info .body {position: relative;overflow: hidden;}
    .info .desc {position: relative;margin: 13px 0 0 90px;height: 75px;}
    .desc .ellipsis {overflow: hidden;text-overflow: ellipsis;white-space: nowrap;}
    .desc .jibun {font-size: 11px;color: #888;margin-top: -2px;}
    .info .img {position: absolute;top: 6px;left: 5px;width: 73px;height: 71px;border: 1px solid #ddd;color: #888;overflow: hidden;}
    .info:after {content: '';position: absolute;margin-left: -12px;left: 50%;bottom: 0;width: 22px;height: 12px;background: url('http://t1.daumcdn.net/localimg/localimages/07/mapapidoc/vertex_white.png')}
    .info .link {color: #5085BB;}
</style>      
      

app/views/products/index_penalty.html.erb
        <!-- start head bottom -->
      <div class="bottom">
        <div class="left">
          <h1>등록된 단속구역 목록</h1>
        </div>
        <div class="right">
          <!--<h1>dashboard /</h1>-->
          <!--<a href="#">page name</a>-->
        </div>
      </div>
      <!-- end head bottom -->
      

<div class ="m-3"><div id="map" style="width:100%;height:300px;z-index: 0;"></div></div>

<script type="text/javascript" src="//dapi.kakao.com/v2/maps/sdk.js?appkey=<%= ENV['DAUM_MAP_API'] %>"></script>
      
      
<div class="card-body">
  <h3 class="m-b-lg"></h3>
    <div class="row">
<% @products.reverse.each do |product|%>
<% if product.area_type.eql?("단속구역") %>
     <div class="card col-md-4">
  	   <img class="card-img-top" src="<%= product.image_address.thumb.url %>" >
  	 <div class="card-boby text"><br>
  	 <div class="card-block">
  		<h4 class="card-title">장소명 : <%=product.area_name%></h4>
  		
  		    장소 설명 : <%=product.description%> <br>
  		</div>
  		<div class="card-block">
  		    <center>
  	      <%= link_to '자세히보기', product_path(product), class: "btn btn-primary"%>
  	      </center>
  		</div>
  	  </div>
  	</div><!-- END column -->
<% end %>
<% end %>
  </div><!-- .row -->
</div>

<!--<div id = "title" class = "row">-->
<!--  <@% @products.each do |product|%>-->
<!--  <@% if product.area_type.eql?("단속구역") %>-->
<!--  <div class="card col-md-3">-->
<!--    <img class="card-img-top" src="<@%= product.image_address.thumb.url %>" >-->
<!--    <div class="card-body text-left">-->
      <!--<h5 class="card-title" data_id=1><span><%#=product.area_type%></span></h5>-->
<!--      <p class="card-text">장소명 : <@%=product.area_name%></p>-->
<!--      <p class="card-text">장소 설명 : <@%=product.description%></p>-->
<!--      <@%= link_to '자세히보기', product_path(product), class: "btn btn-primary"%>-->
<!--    </div>-->
<!--  </div>-->
<!--<@% end %>-->
<!--<@% end %>-->
<!--</div>-->

<% content_for 'javascript_content' do %>
<%= javascript_include_tag params[:controller] %>
<% end %>

<script>
    console.log("content_for");
</script>    



<script>


var mapContainer = document.getElementById('map'), // 지도의 중심좌표
    mapOption = { 
        center: new daum.maps.LatLng(37.4977796, 127.0755652), // 지도의 중심좌표
        level: 4 // 지도의 확대 레벨
    }; 

var map = new daum.maps.Map(mapContainer, mapOption); // 지도를 생성합니다


// HTML5의 geolocation으로 사용할 수 있는지 확인합니다 
if (navigator.geolocation) {
    
    // GeoLocation을 이용해서 접속 위치를 얻어옵니다
    navigator.geolocation.getCurrentPosition(function(position) {
        
        var lat = position.coords.latitude, // 위도
            lon = position.coords.longitude; // 경도
        
        var locPosition = new daum.maps.LatLng(lat, lon), // 마커가 표시될 위치를 geolocation으로 얻어온 좌표로 생성합니다
            message = '<center><div style="padding:5px;">현재 위치!</div></center>'; // 인포윈도우에 표시될 내용입니다
        
        // 마커와 인포윈도우를 표시합니다
        displayMarker(locPosition, message);
            
      });
    
} else { // HTML5의 GeoLocation을 사용할 수 없을때 마커 표시 위치와 인포윈도우 내용을 설정합니다
    
    var locPosition = new daum.maps.LatLng(33.450701, 126.570667),    
        message = 'geolocation을 사용할수 없어요..'
        
    displayMarker(locPosition, message);
}

// 지도에 마커와 인포윈도우를 표시하는 함수입니다
function displayMarker(locPosition, message) {

    // 마커를 생성합니다
    var marker = new daum.maps.Marker({  
        map: map, 
        position: locPosition
    }); 
    
    var iwContent = message, // 인포윈도우에 표시할 내용
        iwRemoveable = true;

    // 인포윈도우를 생성합니다
    var infowindow = new daum.maps.InfoWindow({
        content : iwContent,
        removable : iwRemoveable
    });
    
    // 인포윈도우를 마커위에 표시합니다 
    infowindow.open(map, marker);
    
    // 지도 중심좌표를 접속위치로 변경합니다
    map.setCenter(locPosition);      
}    











var positions = [];
// 커스텀 오버레이에 표시할 컨텐츠 입니다
// 커스텀 오버레이는 아래와 같이 사용자가 자유롭게 컨텐츠를 구성하고 이벤트를 제어할 수 있기 때문에
// 별도의 이벤트 메소드를 제공하지 않습니다 
            //'                <div><a href="http://www.kakaocorp.com/main" target="_blank" class="link">홈페이지</a></div>' + 
// 마커 위에 커스텀오버레이를 표시합니다
// 마커를 중심으로 커스텀 오버레이를 표시하기위해 CSS를 이용해 위치를 설정했습니다
<% @products.each do |product|%>
        var content = '<div class="wrap">' + 
            '    <div class="info">' + 
            '        <div class="title" value= "<%= product.id%>">' + 
            '            <%= product.area_type%>-신고누적(<%= product.likes.count %>)' + 
            '            <div class="close"  title="닫기"></div>' + 
            '        </div>' + 
            '        <div class="body">' + 
            '            <div class="img">' +
            '                <img src="<%= product.image_address%>" width="73" height="70">' +
            '           </div>' + 
            '            <div class="desc">' + 
            '                <div class="ellipsis"><h5><%= product.area_name%></h5></div>' + 
            '    <a href = "/products/<%= product.id %>" class="btn btn-info btn-sm">자세히보기</a>' +
            '            </div>' + 
            '            </div>' + 
            '        </div>' + 
            '    </div>' +    
            '</div>'; 
        var m = "<%= product.area_type%>";
        console.log(m)
    positions.push(
        {
        content: content,
        latlng: new daum.maps.LatLng(<%=product.latitude %>, <%=product.longitude %>),
        imarker: m
        }
    );
<% end %>

console.log(overlay);
var overlay = [];
for (var i = 0 ; i < positions.length; i ++) {
    
    if  (positions[i].imarker=="단속구역") // "<@%= asset_path 'g2.png' %>"
                            
    var markerImageUrl = "<%= asset_path 'penalty.png' %>"
	    markerImageSize = new daum.maps.Size(30, 41) // 마커 이미지의 크기
	    markerImageOptions = { 
	        offset : new daum.maps.Point(16, 40)// 마커 좌표에 일치시킬 이미지 안의 좌표
	    };

	// 마커 이미지를 생성한다
	var markerImage = new daum.maps.MarkerImage(markerImageUrl, markerImageSize, markerImageOptions);

    var marker = new daum.maps.Marker({
        map: map, 
        image : markerImage,
        position: positions[i].latlng,
        title: i
    });

    
    console.log(marker);
   overlay[i]= new daum.maps.CustomOverlay({
            content: positions[i].content,
            position: positions[i].latlng
    });
    console.log(overlay.length);
    
    (function(marker, overlay) {
        // 마커에 click 이벤트를 등록하고 마우스 오버 시 인포윈도우를 표시합니다.
           
    daum.maps.event.addListener(marker, 'click', function() {
            var selectedMarker = marker;
            for (var j = 0; j < positions.length; j ++) {
            if (selectedMarker || selectedMarker == marker) {
                overlay[j].setMap(null);
            };
            };
            overlay[marker.getTitle()].setMap(map);
        });
// 커스텀 오버레이를 닫기 위해 호출되는 함수입니다 
        // 마커에 mouseout 이벤트를 등록하고 마우스 아웃 시 인포윈도우를 닫습니다
        daum.maps.event.addListener(marker, 'mouseout', function() {
          $( ".close" ).click( function() {
           overlay[marker.getTitle()].setMap(null); 
            });
        });
    })(marker, overlay);
    
};
</script>
  

<style>
    .wrap {position: absolute;left: 0;bottom: 40px;width: 288px;height: 132px;text-align: left;overflow: hidden;font-size: 12px;font-family: 'Malgun Gothic', dotum, '돋움', sans-serif;line-height: 1.5;}
    .wrap {padding: 0;margin-left: -144px;}
    .wrap .info {width: 286px;height: 120px;border-radius: 5px;border-bottom: 2px solid #ccc;border-right: 1px solid #ccc;overflow: hidden;background: #fff;}
    .wrap .info:nth-child(1) {border: 0;box-shadow: 0px 1px 2px #888;}
    .info .title {padding: 5px 0 0 10px;height: 30px;background: #eee;border-bottom: 1px solid #ddd;font-size: 18px;font-weight: bold;}
    .info .close {position: absolute;top: 10px;right: 10px;color: #888;width: 17px;height: 17px;background: url('http://t1.daumcdn.net/localimg/localimages/07/mapapidoc/overlay_close.png');}
    .info .close:hover {cursor: pointer;}
    .info .body {position: relative;overflow: hidden;}
    .info .desc {position: relative;margin: 13px 0 0 90px;height: 75px;}
    .desc .ellipsis {overflow: hidden;text-overflow: ellipsis;white-space: nowrap;}
    .desc .jibun {font-size: 11px;color: #888;margin-top: -2px;}
    .info .img {position: absolute;top: 6px;left: 5px;width: 73px;height: 71px;border: 1px solid #ddd;color: #888;overflow: hidden;}
    .info:after {content: '';position: absolute;margin-left: -12px;left: 50%;bottom: 0;width: 22px;height: 12px;background: url('http://t1.daumcdn.net/localimg/localimages/07/mapapidoc/vertex_white.png')}
    .info .link {color: #5085BB;}
</style>      
      

app/views/products/like_product.js.erb
    //$('.like').text("좋아요 취소").toggleClass("btn-warning btn-info");

    var like_count = parseInt($('.like-count').text());
    
    console.log(<%= @like.frozen? %>);
    if(<%= @like.frozen? %>){
    // 좋아요가 취소된 경우
    // 좋아요 취소버튼 -> 좋아요 버튼
        like_count = like_count - 1;
        $('.like').html(`신고하기(<span class='like-count'>${like_count}</span>)`).attr('class', "btn btn-danger like");
        console.log("신고");
    }else{
    // 좋아요가 새로 눌린 경우
    // 좋아요 버튼 -> 좋아요
        like_count = like_count + 1;
        $('.like').html(`신고취소(<span class='like-count'>${like_count}</span>)`).attr('class', "btn btn-warning like");
        console.log("취소");
    }

console.log(like_count);

app/views/products/new_map.html.erb
        <!-- start head bottom -->
      <div class="bottom">
        <div class="left">
          <h1>등록하기</h1>
        </div>
        <div class="right">
          <h1>dashboard /</h1>
          <a href="#">page name</a>
        </div>
      </div>

(:area_type,:area_name,:address,:latitude,:longitude,:description,:image_address  
  
  
<%= render 'map', product: @product %>

<form action = "/product_map" method = "POST">
    <input type = "hidden" name = "authenticity_token" value ="<%= form_authenticity_token%>">
    <input type = "text" name ="area_name" placeholder = "제목">
    <input type = "text" name ="address" placeholder = "주소">
    <input type = "text" name ="description" placeholder = "내용">
    <input type = "submit" value = "등록하기">
</form>


<%= link_to 'Back', products_path, class: ""%>

  
<% content_for 'javascript_content' do%>
<%= javascript_include_tag params[:controller] %>
<%end%>